app:
    baseUrl: http://localhost:3001
server:
    port: 8080
    servlet:
        context-path: /api
spring:
    application:
        name: Chatop
    database: mysql
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${JDBC_DATABASE_PASSWORD}
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
    resources:
        static-locations: classpath:/static/images/
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
